### PR TITLE
Update rxjava version

### PR DESCRIPTION
**Pull request by rworsnop**
Issue #29 
I've signed the CLA

### CODE REVIEW

**Comment by HugoCrd** [comment]
Hi, what are your plans about this PR?
Would be great to have a published version with 1.0.4 RxJava ;)

**Comment by petermd** [comment]
Agreed. Sorry about the delay. I'll close off the remaining 0.20 stuff and hopefully do the update this weekend.

-Peter

**Comment by HugoCrd** [comment]
Cool ! Thanks for your job !

**Comment by petermd** [comment]
upgraded via #43 instead - apologies for my tardy follow up here

**Pull request closed without merging**
